[package]
name = "flutter-sys"
version = "0.1.0"
edition = "2021"

[lib]
# TODO(jiahaog): Generated bindings fail these tests.
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
bindgen = "0.64.0"
